packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@biomejs/biome": 2.2.7
  "@testing-library/jest-dom": 6.9.1
  "@testing-library/react": 16.3.0
  "@testing-library/user-event": 14.6.1
  "@vitejs/plugin-react": 5.1.1
  cspell: 9.3.2
  jsdom: 27.2.0
  knip: 5.70.2
  vitest: 3.2.4
