packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@biomejs/biome": 2.2.7
  "@testing-library/jest-dom": 6.9.1
  "@testing-library/react": 16.3.1
  "@testing-library/user-event": 14.6.1
  "@vitejs/plugin-react": 5.1.2
  cspell: 9.6.0
  jsdom: 27.4.0
  knip: 5.80.2
  vitest: 3.2.4
