packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@biomejs/biome": 2.2.6
  "@testing-library/jest-dom": 6.9.1
  "@testing-library/react": 16.3.0
  "@testing-library/user-event": 14.6.1
  "@vitejs/plugin-react": 5.0.4
  cspell: 9.2.1
  jsdom: 27.0.0
  knip: 5.66.0
  vitest: 3.2.4
