name: e2e テスト
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NEXT_PUBLIC_SUPABASE_URL: http://127.0.0.1:14321
  NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
  SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU

jobs:
  e2e-test:
    timeout-minutes: 60
    # playwright の vrt で環境が異なると差分が出る可能性が高いため、ローカルと同じ macOS で実行する
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [chromium, webkit, "Mobile Chrome", "Mobile Safari"]
      fail-fast: false
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: supabase cli のセットアップ
        uses: supabase/setup-cli@v1
        with:
          version: latest
      # 時間短縮のためテストで不要なサービスは除外して supabase を起動
      - name: Supabase 起動
        run: supabase start -x gotrue,storage-api,imgproxy,kong,inbucket,postgrest,postgres-meta,studio,edge-runtime,logflare,vector,supavisor

      - name: pnpm のセットアップ
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Node.js セットアップ
        uses: actions/setup-node@v4
        with:
          node-version-file: "./.node-version"
          cache: "pnpm"
      - name: パッケージインストール
        run: pnpm install
      - name: Playwright ブラウザインストール
        run: pnpm --filter e2e exec playwright install --with-deps

      - name: DB リセット
        run: pnpm dlx supabase db reset

      - name: Web ビルド
        run: pnpm --filter web run build
      - name: e2e テスト
        run: pnpm --filter e2e run test --project="${{ matrix.project }}"

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.project }}
          path: packages/e2e/playwright-report/
          retention-days: 1
